spring.application.name=task-tracker-backend

jwt.access-token-ttl=24h

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties[spring.json.add.type.headers]=false