spring.application.name=task-tracker-backend

spring.datasource.url=jdbc:postgresql://localhost:${DB_EXTERNAL_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}