spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

logging.level.root=INFO
logging.file.name=/app/logs/task-tracker-backend.log
logging.charset.file=UTF-8
logging.threshold.file=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n

logging.logback.rollingpolicy.file-name-pattern=/app/logs/archive/task-tracker-backend.%d{yyyy-MM-dd}.%i.log.gz

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

internal.api.key=${INTERNAL_API_KEY}