spring.datasource.url=jdbc:postgresql://localhost:5432/task-tracker
spring.datasource.username=dev
spring.datasource.password=password

jwt.secret=example-OgGx02bPzdNPFiYahNvORXu5jWRUcc1eOMPNrtW0FAe

logging.level.root=INFO
logging.level.com.prplhd.tasktracker=DEBUG
logging.charset.console=UTF-8
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n

spring.kafka.bootstrap-servers=localhost:9092